version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "express"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1mqlemgl17u4u"
s3_prefix = "express"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
