AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  vin-app
  Sample Template for vin-app
Globals:
  Function:
    Timeout: 10
    Tracing: Active
  Api:
    TracingEnabled: True
Resources:
  ApplicantTrackingSystemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: AppServer/
      Handler: app.handler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Events:
        ApplicantTrackingSystem:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
Outputs:
  ApplicantTrackingSystemApi:
    Description: "API Gateway endpoint URL for Prod stage for Applicant Tracking System website application"
    Value: !Sub "https://${ServerlessRestApi}.api.${AWS::Region}.amazonaws.com/ApplicantTrackingSystem/"
  ApplicantTrackingSystemFunction:
    Description: "This website application will track and manage applicants of DENR"
    Value: !GetAtt ApplicantTrackingSystemFunction.Arn
  ApplicantTrackingSystemFunctionIamRole:
    Description: "Implicit IAM Role created for Applicant Tracking System function"
    Value: !GetAtt ApplicantTrackingSystemFunctionRole.Arn
